# Generated by Django 4.0.3 on 2022-04-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='workers',
            field=models.ManyToManyField(blank=True, to='core.worker'),
        ),
    ]
