# Generated by Django 4.0.3 on 2022-04-06 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_shift_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 6, 0, 49, 17, 557476, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
