# Generated by Django 4.0.3 on 2022-04-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shift_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='available',
            new_name='is_available',
        ),
    ]
